version: "3.8"

services:
  neo4j:
    image: neo4j:5
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=neo4j/password
    volumes:
      - neo4j_data:/data

  api:
    build: ./app
    ports:
      - "8000:8000"
    depends_on:
      - neo4j
    volumes:
      - ./app:/app
      - media_files:/app/media
    working_dir: /app

  mongodb:
    image: mongo:6
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  neo4j_data:
  mongo_data:
  media_files:
  